# Install Library

In [1]:
!pip install numpy pandas matplotlib tqdm

# Import

In [2]:
import numpy as np 
import pandas as pd

In [3]:
#load dataset
df = pd.read_csv("/Users/andrewhowe/Documents/Phong_PCLA/ASSISTmentProject/Dataset/2012-2013-data-with-predictions-4-final-small.csv",low_memory=False)

In [4]:
df.head()

Unnamed: 0  problem_log_id                                          skill  \
0     1934459       142682351                                            NaN   
1      828989       144979964                             Polynomial Factors   
2     3076134       137173833  Order of Operations +,-,/,* () positive reals   
3     4960611       140148312                        Order of Operations All   
4      225578       143207673                                            NaN   

   problem_id  user_id  assignment_id  assistment_id           start_time  \
0      662668   191280         750770         417348  2013-03-21 13:13:26   
1      134804   176639         794836          72576  2013-05-20 11:48:52   
2      547854   126455         559982         334628  2012-09-12 06:34:31   
3       85025   200134         639336          46733  2012-12-11 09:18:33   
4      464908   212331         759232         272447  2013-04-08 15:07:31   

                  end_time problem_type            ...              \
0  2013-03-21 13:13:33.713     choose_1            ...               
1  2013-05-20 11:49:51.823      algebra            ...               
2  2012-09-12 06:34:35.233      algebra            ...               
3  2012-12-11 09:18:45.977      algebra            ...               
4  2013-04-08 15:08:10.018     choose_1            ...               

   overlap_time  template_id  answer_id           answer_text first_action  \
0          7702       417348        NaN               hunting            0   
1         37126        61641        NaN                   x+2            0   
2          4202       334628        NaN                     4            0   
3         12961        29981        NaN                    29            0   
4         38948       272447        NaN  1 - P(Type II Error)            0   

   problemlogid  Average_confidence(FRUSTRATED) Average_confidence(CONFUSED)  \
0     142682351                        0.361323                     0.000000   
1     144979964                        0.413033                     0.000000   
2     137173833                        0.361323                     0.000000   
3     140148312                        0.361323                     0.978947   
4     143207673                        0.361323                     0.000000   

   Average_confidence(CONCENTRATING)  Average_confidence(BORED)  
0                           0.766925                   0.000000  
1                           0.766925                   0.306590  
2                           0.766925                   0.000000  
3                           0.336529                   0.442968  
4                           0.766925                   0.000000  

[5 rows x 36 columns]

In [5]:
df.describe()

Unnamed: 0  problem_log_id     problem_id        user_id  \
count  1.000000e+05    1.000000e+05  100000.000000  100000.000000   
mean   3.060314e+06    1.414921e+08  367916.740490  177182.341320   
std    1.768400e+06    2.690561e+06  219704.841499   31660.907685   
min    6.200000e+01    1.368432e+08      13.000000   61394.000000   
25%    1.531890e+06    1.391667e+08  128259.750000  172027.000000   
50%    3.058905e+06    1.414739e+08  416809.000000  179190.000000   
75%    4.589200e+06    1.438234e+08  564200.750000  197395.000000   
max    6.123203e+06    1.461395e+08  767081.000000  228213.000000   

       assignment_id  assistment_id       original       correct  \
count  100000.000000  100000.000000  100000.000000  100000.00000   
mean   677038.725430  219879.642890       0.950110       0.67580   
std     94188.666154  139430.426288       0.217719       0.46786   
min    267520.000000      13.000000       0.000000       0.00000   
25%    586047.000000   68789.500000       1.000000       0.00000   
50%    678400.000000  239918.000000       1.000000       1.00000   
75%    766768.750000  346677.000000       1.000000       1.00000   
max    833014.000000  492551.000000       1.000000       1.00000   

        bottom_hint     hint_count            ...                 school_id  \
count  99029.000000  100000.000000            ...              99998.000000   
mean       0.120278       0.339160            ...               6938.851007   
std        0.325288       0.988605            ...               3318.638191   
min        0.000000       0.000000            ...                  1.000000   
25%        0.000000       0.000000            ...               5260.000000   
50%        0.000000       0.000000            ...               5978.000000   
75%        0.000000       0.000000            ...               9446.000000   
max        1.000000      10.000000            ...              12421.000000   

       overlap_time    template_id     answer_id  first_action  problemlogid  \
count  1.000000e+05  100000.000000  1.310000e+02  100000.00000  1.000000e+05   
mean   4.871557e+04  208620.214870  4.943771e+05       0.06115  1.414921e+08   
std    9.035051e+04  145802.934238  3.760727e+05       0.26251  2.690561e+06   
min    2.390000e+02      13.000000  1.000000e+00       0.00000  1.368432e+08   
25%    9.484000e+03   52497.000000  1.310345e+05       0.00000  1.391667e+08   
50%    2.239200e+04  239538.000000  3.956780e+05       0.00000  1.414739e+08   
75%    5.503425e+04  343460.000000  9.386540e+05       0.00000  1.438234e+08   
max    1.008000e+07  492551.000000  1.133329e+06       2.00000  1.461395e+08   

       Average_confidence(FRUSTRATED)  Average_confidence(CONFUSED)  \
count                   100000.000000                 100000.000000   
mean                         0.389123                      0.044031   
std                          0.102165                      0.190694   
min                          0.361323                      0.000000   
25%                          0.361323                      0.000000   
50%                          0.361323                      0.000000   
75%                          0.361323                      0.000000   
max                          0.867133                      1.000000   

       Average_confidence(CONCENTRATING)  Average_confidence(BORED)  
count                      100000.000000              100000.000000  
mean                            0.682719                   0.255543  
std                             0.171215                   0.285350  
min                             0.170732                   0.000000  
25%                             0.766925                   0.000000  
50%                             0.766925                   0.221484  
75%                             0.766925                   0.442968  
max                             0.766925                   1.000000  

[8 rows x 28 columns]

In [6]:
df.columns

Index(['Unnamed: 0', 'problem_log_id', 'skill', 'problem_id', 'user_id',
       'assignment_id', 'assistment_id', 'start_time', 'end_time',
       'problem_type', 'original', 'correct', 'bottom_hint', 'hint_count',
       'actions', 'attempt_count', 'ms_first_response', 'tutor_mode',
       'sequence_id', 'student_class_id', 'position', 'type',
       'base_sequence_id', 'skill_id', 'teacher_id', 'school_id',
       'overlap_time', 'template_id', 'answer_id', 'answer_text',
       'first_action', 'problemlogid', 'Average_confidence(FRUSTRATED)',
       'Average_confidence(CONFUSED)', 'Average_confidence(CONCENTRATING)',
       'Average_confidence(BORED)'],
      dtype='object')

In [7]:
import time
import datetime
from tqdm import tqdm

Calculate the time taken per question in seconds. Each row is a question, which has start time and end time.

In [8]:
start_time = df["start_time"]
start_time.head()

0    2013-03-21 13:13:26
1    2013-05-20 11:48:52
2    2012-09-12 06:34:31
3    2012-12-11 09:18:33
4    2013-04-08 15:07:31
Name: start_time, dtype: object

In [9]:
end_time = df["end_time"]
end_time.head()

0    2013-03-21 13:13:33.713
1    2013-05-20 11:49:51.823
2    2012-09-12 06:34:35.233
3    2012-12-11 09:18:45.977
4    2013-04-08 15:08:10.018
Name: end_time, dtype: object

Convert the start time and end time to Unix to calculate.

In [10]:
start_time_unix = []
for i in tqdm(range(len(start_time))):
    try:
        start_time_unix.append(time.mktime(datetime.datetime.strptime(start_time[i], "%Y-%m-%d %H:%M:%S").timetuple()))
    except:
        start_time_unix.append(np.NaN)
start_time_unix = np.array(start_time_unix)
start_time_unix[0:5]

100%|██████████| 100000/100000 [00:03<00:00, 25098.11it/s]


array([1.36383921e+09, 1.36901813e+09, 1.34739927e+09, 1.35518511e+09,
       1.36540125e+09])

In [11]:
end_time_unix = []
for i in tqdm(range(len(end_time))):
    try:
        end_time_unix.append(time.mktime(datetime.datetime.strptime(end_time[i], "%Y-%m-%d %H:%M:%S.%f").timetuple()))
    except:
        end_time_unix.append(np.NaN)
end_time_unix = np.array(end_time_unix)
end_time_unix[:5]

100%|██████████| 100000/100000 [00:04<00:00, 23874.16it/s]


array([1.36383921e+09, 1.36901819e+09, 1.34739928e+09, 1.35518512e+09,
       1.36540129e+09])

In [12]:
question_time = end_time_unix - start_time_unix

In [13]:
df["question_time"] = question_time

Clean the data with question time greater than 0, and less than 5 mins

In [14]:
df = df[df["question_time"] > 0] # clean all the data with question time <=0

In [15]:
df = df[df["question_time"] < 300 ] # clean all the data with question time >300

In [16]:
df.shape

(95246, 37)

Try to find total session time.
A session is defined by a specific user_id answering multiple questions on the same date. 

In [17]:
start_date = []
start_time = df["start_time"]
for i in range(len(start_time)):
    start_date.append(start_time.iloc[i].split(" ")[0])

In [18]:
df["start_date"] = start_date

In [19]:
df_small = df [["user_id", "start_date", "question_time","Average_confidence(FRUSTRATED)",
       "Average_confidence(CONFUSED)", "Average_confidence(CONCENTRATING)",
       "Average_confidence(BORED)", 'ms_first_response', 'hint_count', 'actions' ]]
df_small.head()

user_id  start_date  question_time  Average_confidence(FRUSTRATED)  \
0   191280  2013-03-21            7.0                        0.361323   
1   176639  2013-05-20           59.0                        0.413033   
2   126455  2012-09-12            4.0                        0.361323   
3   200134  2012-12-11           12.0                        0.361323   
4   212331  2013-04-08           39.0                        0.361323   

   Average_confidence(CONFUSED)  Average_confidence(CONCENTRATING)  \
0                      0.000000                           0.766925   
1                      0.000000                           0.766925   
2                      0.000000                           0.766925   
3                      0.978947                           0.336529   
4                      0.000000                           0.766925   

   Average_confidence(BORED)  ms_first_response  hint_count  \
0                   0.000000               7702           0   
1                   0.306590              37126           5   
2                   0.000000               4202           0   
3                   0.442968              12961           0   
4                   0.000000              38948           0   

                                             actions  
0  --- \n- - start\n  - 1363886006860\n  - "15752...  
1  --- \n- - start\n  - 1369064932485\n  - "18426...  
2  --- \n- - start\n  - 1347446071864\n  - "93194...  
3  --- \n- - start\n  - 1355235513383\n  - "71770...  
4  --- \n- - start\n  - 1365448051062\n  - "82882...

In [20]:
session = df_small.groupby(["user_id","start_date"])["question_time"].sum()
session.head(15)

user_id  start_date
61394    2012-09-16      4.0
         2012-09-25      4.0
         2012-10-09     37.0
         2012-10-15     11.0
         2012-11-10     20.0
         2012-12-02     70.0
         2012-12-10     41.0
         2013-01-04      6.0
         2013-01-11    221.0
         2013-05-21     12.0
         2013-08-20     53.0
74601    2012-12-10     31.0
         2012-12-17     64.0
         2013-01-29     15.0
         2013-03-26     22.0
Name: question_time, dtype: float64

In [21]:
session_df = session.to_frame()
session_df.reset_index(inplace=True)
session_df.head(5)

user_id  start_date  question_time
0    61394  2012-09-16            4.0
1    61394  2012-09-25            4.0
2    61394  2012-10-09           37.0
3    61394  2012-10-15           11.0
4    61394  2012-11-10           20.0

In [22]:
session_df.shape

(76937, 3)

Clean sessions to be 15 minutes at least but cap sessions at an hour.

In [23]:
session_df = session_df[session_df["question_time"] < 3600 ]
session_df.shape

(76937, 3)

In [24]:
session_df = session_df[session_df["question_time"] > 60 ]
session_df.shape

(24099, 3)

In [25]:
session_df.head()

user_id  start_date  question_time
5     61394  2012-12-02           70.0
8     61394  2013-01-11          221.0
12    74601  2012-12-17           64.0
20    75241  2012-12-17          160.0
23    76592  2012-10-12           81.0

In [26]:
session_count = df_small.groupby(["user_id","start_date"])["question_time"].count()
session_count_df = session_count.to_frame()
session_count_df.reset_index(inplace=True)
session_count_df.head()

user_id  start_date  question_time
0    61394  2012-09-16              1
1    61394  2012-09-25              1
2    61394  2012-10-09              1
3    61394  2012-10-15              1
4    61394  2012-11-10              1

In [27]:
session_count_df["question_time"].unique()

array([ 1,  2,  3,  5, 11, 10, 13,  4,  6,  7,  8,  9, 16, 12, 15, 23, 17,
       14, 19])

NOTES FOR NEXT SESSION: 
Parse out the different response times for the actions and then plot to see if response times get significantly longer as the session progresses.
Start analysis on the affect detectors and the amount of time that it's taking throughout a session. Then bin the data to see more easily with standard error bars and means for each column. 

Try to clean through amount of questions and amount of time
